---
name: Arduino CI

on: [push, pull_request]

jobs:
  arduino_ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Run Arduino-CI tests
        run: scripts/testAndBuild.sh
